### ISSUE TITLE
Web settings are not persistent when configuration exists in file. (only sending ETA)

### ISSUE THREAD

**Issue by Mac2712** [tpmullan/OctoPrint-DetailedProgress#8]
HI I have just loaded the latest version of DetailedProgress looks promising. 
Its only adding the ETA line into the Gcode stream to the printer running Merlin 2.0.1, old version worked fine before

**Comment by jhillyerd** [comment]
I have a similar problem, mine is configured (according to web UI) to send:

```
{filename}
ETL {printTimeLeft}
ETA {ETA]
```

but all that shows on my printers screen is `Good accuracy`

This is what I see in config.yaml:

```
    detailedprogress:
        all_messages:
        - '{filename}'
        - ETL {printTimeLeft}
        - ETA {ETA}
        messages:
        - '{accuracy} accuracy'
        time_to_change: '5'
```

So probably related to #7 as well.

**Comment by tpmullan** [comment]
I will look into this.  I have only set the config from the settings.  It sounds like it is not updating the config file

**Comment by tpmullan** [comment]
I do not see anywhere in the code that is directly interfacing with the config file.   It looks like it is imported as a dictionary and the defaults are added.  I personally do not ever manually edit the configuration file since it is a pain, and only use the web settings, so I have not seen this bug.  Currently I am considering completely deprecating editing the config file.

Can someone that is facing this issue test removing those sections from the configuration file then using the web interface only to make changes?

**Comment by jhillyerd** [comment]
I just tried deleting ETL via the web interface, and it updated to:

```
   detailedprogress:
        all_messages:
        - '{filename}'
        - ETA {ETA}
        messages:
        - ETL {printTimeLeft}
        time_to_change: '5'
```

Prior to https://github.com/tpmullan/OctoPrint-DetailedProgress/issues/8#issuecomment-626182399 - I had deleted the accuracy line via web, so for some reason it overwrites messages: with the deleted entry.  The content of all_messages is correct (in terms of what I want the be displayed), but is not used.

I will try removing the detailedprogress section from the config entirely.
